<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24308" started-at="2020-07-14T03:00:52Z" finished-at="2020-07-14T03:01:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24308" started-at="2020-07-14T03:00:52Z" finished-at="2020-07-14T03:01:16Z">
      <class name="TestNGDemo.DataProviderDemo">
        <test-method status="FAIL" signature="LoginToApplication(java.lang.String, java.lang.String)[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="LoginToApplication" duration-ms="7694" started-at="2020-07-14T03:00:52Z" data-provider="WordPressLogin" finished-at="2020-07-14T03:00:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login to Appliation expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login to Appliation expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at TestNGDemo.DataProviderDemo.LoginToApplication(DataProviderDemo.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="tearDown" is-config="true" duration-ms="232" started-at="2020-07-14T03:00:59Z" finished-at="2020-07-14T03:01:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="LoginToApplication(java.lang.String, java.lang.String)[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="LoginToApplication" duration-ms="7697" started-at="2020-07-14T03:01:00Z" data-provider="WordPressLogin" finished-at="2020-07-14T03:01:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="tearDown" is-config="true" duration-ms="167" started-at="2020-07-14T03:01:07Z" finished-at="2020-07-14T03:01:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LoginToApplication(java.lang.String, java.lang.String)[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="LoginToApplication" duration-ms="8317" started-at="2020-07-14T03:01:08Z" data-provider="WordPressLogin" finished-at="2020-07-14T03:01:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login to Appliation expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login to Appliation expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at TestNGDemo.DataProviderDemo.LoginToApplication(DataProviderDemo.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestNGDemo.DataProviderDemo@cb5822]" name="tearDown" is-config="true" duration-ms="141" started-at="2020-07-14T03:01:16Z" finished-at="2020-07-14T03:01:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestNGDemo.DataProviderDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
